name = "MissingStrategies"
uuid = "e455a6d6-8373-11eb-38a5-df3e63e3f6fc"
authors = ["Thomas Wutzler <bgctw@arcor.de>"]
version = "0.1.0"

[deps]
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"

[compat]
julia = "1.5"
Missings = "0.4"
SimpleTraits = "0.9"
